def get_cities():
    cities = [
        # "Toronto" :too big, done seperately.
        # "Ottawa",
        "Prince Edward County",
        "Quinte West",
        "Haldimand County",
        "Norfolk County",
        "Clarence-Rockland",
        "Kawartha Lakes",
        "Leamington",
        "Temiskaming Shores",
        "Greater Sudbury",
        "Port Colborne",
        "Elliot Lake",
        "Thorold",
        "Dryden",
        "St. Thomas",
        "Kenora",
        "Pembroke",
        "Timmins",
        "Welland",
        "Niagara Falls",
        "Orillia",
        "Woodstock",
        "Stratford",
        "Owen Sound",
        "Cornwall",
        "Brockville",
        "Pickering",
        "Sarnia",
        "Sault Ste. Marie",
        "Chatham",
        "Brantford",
        "Brant",
        "Vaughan",
        "North Bay",
        "Belleville",
        "Cambridge",
        "Windsor",
        "Thunder Bay",
        "Peterborough",
        "Richmond Hill",
        "Markham",
        "Oshawa",
        "St. Catharines",
        "Brampton",
        "Waterloo",
        "Burlington",
        "Kitchener",
        "Barrie",
        "Kingston",
        "Guelph",
        "Hamilton",
        "London",
        "Mississauga"
    ]
    return cities